#version 450
precision highp float;

layout (set = 0, binding = 0, r32f) uniform image2D noise_texture;

float random(vec2 st) {
    return fract(sin(dot(st, vec2(12.9898,78.233))) * 43758.5453123);
}

void main() {
    vec2 i = vec2(gl_GlobalInvocationID.xy);
    vec4 rnd = vec4(
        random(i),
        random(i + vec2(1.0, 0.0)),
        random(i + vec2(0.0, 1.0)),
        random(i + vec2(1.0, 1.0))
    );
    imageStore(noise_texture, ivec2(gl_GlobalInvocationID.xy), rnd);
}
